name: Environment Variables and Contexts

on:
  push:
  workflow_dispatch:
env:
  MY_GLOBAL_VAR_TAG: "Global Value"
jobs:
  demo-job:
    runs-on: ubuntu-latest
    env:
      My_Tag: "Global Tool"
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Global variable 
        run: echo ${{ env.My_Tag }} 


      - name: Step Level Variable 
        env:
         My_Tag: "Step Tool"
        run: echo $My_Tag

      - name: GitHub Context Information
        
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow Run ID: ${{ github.run_id }}"

     
      - name: Use Secret API Key 
        run: echo "API_KEY=${{ secrets.API_KEY }}"
         
     

     
      - name: Set and Use Dynamic Environment Variable
        run: |
          echo "MY_DYNAMIC_VAR=Dynamic Value" >> $GITHUB_ENV
          echo "MY_DYNAMIC_VAR is: ${{ env.MY_DYNAMIC_VAR }}"

      - name: Final Output Using Dynamic Env Var
        run: |
          echo "Final Dynamic Value: ${{ env.MY_DYNAMIC_VAR }}"
